{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fast-api-test.certificateName" . }}
  labels:
    {{- include "fast-api-test.labels" . | nindent 4 }}
spec:
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: {{ .Values.certManager.issuerKind }}
    group: {{ .Values.certManager.issuerGroup }}
  secretName: {{ include "fast-api-test.certificateName" . }}
  dnsNames:
    - {{ include "fast-api-test.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  usages:
    - server auth
    - client auth
  privateKey:
    rotationPolicy: "Always"
{{- end }}
