{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretsManager.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "fast-api-test.smSecretsName" . }}
  labels:
    {{- include "fast-api-test.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager-cluster-secretstore
    kind: ClusterSecretStore
  data:
    {{- range .Values.externalSecrets.secretsManager.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}
