apiVersion: v2
name: fast-api-test
description: A Helm chart for deploying fast-api-test to AWS EKS
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - fastapi
  - api
maintainers:
  - name: group:default/charlie
dependencies: []
